# Generated by Django 3.2.6 on 2021-08-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=255)),
                ('inscrito', models.IntegerField()),
                ('primerCurso', models.IntegerField()),
                ('matriculado', models.IntegerField()),
                ('graduado', models.IntegerField()),
                ('programaAcademico', models.CharField(max_length=255)),
            ],
        ),
    ]
