# Generated by Django 3.2.6 on 2021-08-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendencia',
            name='graduado',
        ),
        migrations.RemoveField(
            model_name='tendencia',
            name='inscrito',
        ),
        migrations.RemoveField(
            model_name='tendencia',
            name='matriculado',
        ),
        migrations.RemoveField(
            model_name='tendencia',
            name='primerCurso',
        ),
        migrations.RemoveField(
            model_name='tendencia',
            name='programaAcademico',
        ),
        migrations.RemoveField(
            model_name='tendencia',
            name='semestre',
        ),
        migrations.AddField(
            model_name='tendencia',
            name='Graduado',
            field=models.IntegerField(default=None, verbose_name='Graduado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tendencia',
            name='Inscrito',
            field=models.IntegerField(default=None, verbose_name='Inscrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tendencia',
            name='Matriculado',
            field=models.IntegerField(default=None, verbose_name='Matriculado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tendencia',
            name='PrimerCurso',
            field=models.IntegerField(default=None, verbose_name='Primer Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tendencia',
            name='Programa',
            field=models.CharField(default=None, max_length=255, verbose_name='Programa Academico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tendencia',
            name='Semestre',
            field=models.CharField(default=None, max_length=255, verbose_name='Semestre'),
            preserve_default=False,
        ),
    ]
