# Generated by Django 3.2.6 on 2021-08-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0003_auto_20210831_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramasNoOfrecidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProgramaAcademico', models.CharField(max_length=255, null=True, verbose_name='Nombre del Programa Academico')),
                ('CodigoSNIES', models.CharField(max_length=255, null=True, verbose_name='Código SNIES')),
                ('DuracionEnSemestres', models.IntegerField(null=True, verbose_name='Duración en Semestres')),
                ('ResolucionRegistroCalificado', models.CharField(max_length=255, null=True, verbose_name='Resolución Registro Calificado')),
                ('FechaInicioRC', models.CharField(max_length=255, null=True, verbose_name='Fecha de Inicio (RC)')),
                ('DuracionRCAños', models.IntegerField(null=True, verbose_name='Duración (RC) Años')),
                ('FechaFinalizacionRC', models.CharField(max_length=255, null=True, verbose_name='Fechas Finalización (RC)')),
                ('Acreditable', models.CharField(max_length=255, null=True, verbose_name='Acreditable')),
                ('AcreditadoAltaCalidad', models.CharField(max_length=255, null=True, verbose_name='Acreditado Alta Calidad')),
                ('ResolucionAC', models.CharField(max_length=255, null=True, verbose_name='Resolución (AC)')),
                ('DuracionACAños', models.IntegerField(null=True, verbose_name='Duración (AC) Años')),
                ('AcreditacionInternacionalAI', models.CharField(max_length=255, null=True, verbose_name='Acreditación Internacional (AI)')),
                ('FechaInicioAI', models.CharField(max_length=255, null=True, verbose_name='Fechas de Inicio (AI)')),
                ('DuracionAIAños', models.IntegerField(null=True, verbose_name='Duración (AI) Años')),
                ('Año', models.CharField(max_length=255, null=True, verbose_name='Año')),
            ],
        ),
    ]
