# Generated by Django 3.2.6 on 2021-08-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0006_programasofrecidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculadoSegunColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programa', models.CharField(max_length=255, null=True, verbose_name='Programa Académico')),
                ('Oficial', models.IntegerField(null=True, verbose_name='Oficial')),
                ('Privado', models.IntegerField(null=True, verbose_name='Privado')),
                ('SinInformacion', models.IntegerField(null=True, verbose_name='Sin Información')),
                ('Semestre', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
            ],
        ),
    ]
