# Generated by Django 3.2.6 on 2021-08-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0009_matriculadosegunsexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocentesPorDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programa', models.CharField(max_length=255, null=True, verbose_name='Programa Académico')),
                ('CantidadDeDocentes', models.IntegerField(null=True, verbose_name='Cantidad de Docentes')),
                ('Semestre', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
            ],
        ),
    ]
