# Generated by Django 3.2.6 on 2021-08-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0010_docentespordependencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocentesPorFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoDeVinculacion', models.CharField(max_length=255, null=True, verbose_name='Tipo De Vinculación')),
                ('Semestre', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
                ('NivelDeFormacion', models.CharField(max_length=255, null=True, verbose_name='Nivel De Formación')),
                ('CantidadDeDocentes', models.IntegerField(null=True, verbose_name='Cantidad de Docentes')),
            ],
        ),
        migrations.CreateModel(
            name='DocentesPorSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoDeVinculacion', models.CharField(max_length=255, null=True, verbose_name='Tipo De Vinculación')),
                ('Sexo', models.CharField(max_length=255, null=True, verbose_name='Sexo')),
                ('CantidadDeDocentes', models.IntegerField(null=True, verbose_name='Cantidad de Docentes')),
                ('Semestre', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
            ],
        ),
    ]
