# Generated by Django 3.2.6 on 2021-08-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0011_docentesporformacion_docentesporsexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoblacionPorPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramaAcademico', models.CharField(max_length=255, null=True, verbose_name='Programa Académico')),
                ('Inscrito', models.IntegerField(null=True, verbose_name='Inscrito')),
                ('PrimerCurso', models.IntegerField(null=True, verbose_name='Primer Curso')),
                ('Matriculado', models.IntegerField(null=True, verbose_name='Matriculado')),
                ('Graduado', models.IntegerField(null=True, verbose_name='Graduado')),
                ('Año', models.CharField(max_length=255, null=True, verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='PoblacionPorSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(max_length=255, null=True, verbose_name='Nivel')),
                ('Femenino', models.IntegerField(null=True, verbose_name='Femenino')),
                ('Masculino', models.IntegerField(null=True, verbose_name='Masculino')),
                ('Posgrado', models.IntegerField(null=True, verbose_name='Posgrado')),
                ('Pregrado', models.IntegerField(null=True, verbose_name='Pregrado')),
                ('Semestre', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
            ],
        ),
    ]
