# Generated by Django 3.2.6 on 2021-08-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0012_poblacionporprograma_poblacionporsexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramasAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(max_length=255, null=True, verbose_name='Nivel')),
                ('ProgramaAcademico', models.CharField(max_length=255, null=True, verbose_name='ProgramaAcademico')),
                ('Estado', models.CharField(max_length=255, null=True, verbose_name='Estado')),
                ('EstadoRegistroCalificado', models.CharField(max_length=255, null=True, verbose_name='Estado')),
                ('ResolucionRegistroCalificado', models.CharField(max_length=255, null=True, verbose_name='ResolucioRegistroCalificado')),
                ('Año', models.CharField(max_length=255, null=True, verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramasAcademicosAcreditables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramaAcademico', models.CharField(max_length=255, null=True, verbose_name='Programa Academico')),
                ('CodigoSNIES', models.CharField(max_length=255, null=True, verbose_name='Código SNIES')),
                ('EstadoDelPrograma', models.CharField(max_length=255, null=True, verbose_name='Estado del Programa')),
                ('ResolucionRegistroCalificadoRC', models.CharField(max_length=255, null=True, verbose_name='Resolución Registro Calificado')),
                ('DuracionRCAños', models.IntegerField(null=True, verbose_name='Duración (RC) Años')),
                ('AcreditadoAltaCalidadAC', models.CharField(max_length=255, null=True, verbose_name='Acreditado Alta Calidad(AC)')),
                ('ResolucionAC', models.CharField(max_length=255, null=True, verbose_name='Resolución (AC)')),
                ('DuracionACAños', models.IntegerField(null=True, verbose_name='Duración (AC) Años')),
                ('Año', models.CharField(max_length=255, null=True, verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramasAcademicosAcreditados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramaAcademico', models.CharField(max_length=255, null=True, verbose_name='Programa Academico')),
                ('CodigoSNIES', models.CharField(max_length=255, null=True, verbose_name='Código SNIES')),
                ('EstadoDelPrograma', models.CharField(max_length=255, null=True, verbose_name='Estado del Programa')),
                ('ResolucionRegistroCalificadoRC', models.CharField(max_length=255, null=True, verbose_name='Resolución Registro Calificado')),
                ('DuracionRCAños', models.IntegerField(null=True, verbose_name='Duración (RC) Años')),
                ('AcreditadoAltaCalidadAC', models.CharField(max_length=255, null=True, verbose_name='Acreditado Alta Calidad(AC)')),
                ('ResolucionAC', models.CharField(max_length=255, null=True, verbose_name='Resolución (AC)')),
                ('DuracionACAños', models.IntegerField(null=True, verbose_name='Duración (AC) Años')),
                ('Año', models.CharField(max_length=255, null=True, verbose_name='Año')),
            ],
        ),
    ]
