# Generated by Django 3.2.6 on 2021-09-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0013_programasacademicos_programasacademicosacreditables_programasacademicosacreditados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramasAcademicos',
        ),
        migrations.DeleteModel(
            name='ProgramasAcademicosAcreditables',
        ),
        migrations.DeleteModel(
            name='ProgramasAcademicosAcreditados',
        ),
        migrations.DeleteModel(
            name='ProgramasNoOfrecidos',
        ),
        migrations.DeleteModel(
            name='ProgramasOfrecidos',
        ),
    ]
