# Generated by Django 3.2.6 on 2021-09-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0014_auto_20210917_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculadosPregradoColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programa', models.CharField(max_length=255, null=True, verbose_name='Programa Académico')),
                ('Semestre', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
                ('Oficial', models.IntegerField(null=True, verbose_name='Oficial')),
                ('Privado', models.IntegerField(null=True, verbose_name='Privado')),
                ('Na', models.IntegerField(null=True, verbose_name='Na')),
                ('Total', models.IntegerField(null=True, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculadosPregradoEdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programa', models.CharField(max_length=255, null=True, verbose_name='Programa Académico')),
                ('Semeste', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
                ('MenorA17', models.IntegerField(null=True, verbose_name='MenorA17')),
                ('MayorA17MenorA22', models.IntegerField(null=True, verbose_name='MayorA17MenorA22')),
                ('Edad22', models.IntegerField(null=True, verbose_name='Edad22')),
                ('Edad23', models.IntegerField(null=True, verbose_name='Edad23')),
                ('Edad24', models.IntegerField(null=True, verbose_name='Edad24')),
                ('Edad25', models.IntegerField(null=True, verbose_name='Edad25')),
                ('MayorA26MenorA31', models.IntegerField(null=True, verbose_name='MayorA26MenorA31')),
                ('MayorA31', models.IntegerField(null=True, verbose_name='MayorA31')),
                ('Total', models.IntegerField(null=True, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculadosPregradoEstrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programa', models.CharField(max_length=255, null=True, verbose_name='Programa Académico')),
                ('Semeste', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
                ('Estrato0', models.IntegerField(max_length=255, null=True, verbose_name='Estrato0')),
                ('EstratoI', models.IntegerField(max_length=255, null=True, verbose_name='EstratoI')),
                ('EstratoII', models.IntegerField(max_length=255, null=True, verbose_name='EstratoII')),
                ('EstratoIII', models.IntegerField(max_length=255, null=True, verbose_name='EstratoIII')),
                ('EstratoIV', models.IntegerField(max_length=255, null=True, verbose_name='EstratoIV')),
                ('EstratoV', models.IntegerField(max_length=255, null=True, verbose_name='EstratoV')),
                ('EstratoVI', models.IntegerField(max_length=255, null=True, verbose_name='EstratoVI')),
                ('Total', models.IntegerField(null=True, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculadosPregradoSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programa', models.CharField(max_length=255, null=True, verbose_name='Programa Académico')),
                ('Semestre', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
                ('Masculino', models.IntegerField(null=True, verbose_name='Masculino')),
                ('Femenino', models.IntegerField(null=True, verbose_name='Femenino')),
                ('Total', models.IntegerField(null=True, verbose_name='Total')),
            ],
        ),
        migrations.DeleteModel(
            name='DocentesPorDependencia',
        ),
        migrations.DeleteModel(
            name='DocentesPorFormacion',
        ),
        migrations.DeleteModel(
            name='DocentesPorSexo',
        ),
        migrations.DeleteModel(
            name='MatriculadoSegunColegio',
        ),
        migrations.DeleteModel(
            name='MatriculadoSegunEdad',
        ),
        migrations.DeleteModel(
            name='MatriculadoSegunSexo',
        ),
        migrations.DeleteModel(
            name='PoblacionPorPrograma',
        ),
        migrations.DeleteModel(
            name='PoblacionPorSexo',
        ),
        migrations.DeleteModel(
            name='Tendencia',
        ),
    ]
