# Generated by Django 3.2.6 on 2021-09-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0015_auto_20210928_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculadospregradoestrato',
            name='Estrato0',
            field=models.IntegerField(null=True, verbose_name='Estrato0'),
        ),
        migrations.AlterField(
            model_name='matriculadospregradoestrato',
            name='EstratoI',
            field=models.IntegerField(null=True, verbose_name='EstratoI'),
        ),
        migrations.AlterField(
            model_name='matriculadospregradoestrato',
            name='EstratoII',
            field=models.IntegerField(null=True, verbose_name='EstratoII'),
        ),
        migrations.AlterField(
            model_name='matriculadospregradoestrato',
            name='EstratoIII',
            field=models.IntegerField(null=True, verbose_name='EstratoIII'),
        ),
        migrations.AlterField(
            model_name='matriculadospregradoestrato',
            name='EstratoIV',
            field=models.IntegerField(null=True, verbose_name='EstratoIV'),
        ),
        migrations.AlterField(
            model_name='matriculadospregradoestrato',
            name='EstratoV',
            field=models.IntegerField(null=True, verbose_name='EstratoV'),
        ),
        migrations.AlterField(
            model_name='matriculadospregradoestrato',
            name='EstratoVI',
            field=models.IntegerField(null=True, verbose_name='EstratoVI'),
        ),
    ]
