# Generated by Django 3.2.6 on 2021-09-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0016_auto_20210928_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculadospregradoestrato',
            old_name='Semeste',
            new_name='Semestre',
        ),
    ]
