# Generated by Django 3.2.6 on 2021-09-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0017_rename_semeste_matriculadospregradoestrato_semestre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculadospregradoedad',
            old_name='Semeste',
            new_name='Semestre',
        ),
    ]
