# Generated by Django 3.2.6 on 2021-09-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0020_auto_20210928_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculadospregradosexo',
            old_name='Pregrado',
            new_name='Femenino',
        ),
    ]
