# Generated by Django 3.2.6 on 2021-09-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0021_rename_pregrado_matriculadospregradosexo_femenino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculadossexo',
            old_name='Pregrado',
            new_name='Femenino',
        ),
    ]
