# Generated by Django 3.2.6 on 2021-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0025_auto_20210929_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculadosSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_PERIODO', models.CharField(max_length=255, null=True, verbose_name='COD_PERIODO')),
                ('COD_UTP', models.CharField(max_length=255, null=True, verbose_name='COD_UTP')),
                ('ESTUDIANTES', models.IntegerField(null=True, verbose_name='Estudiantes')),
                ('SEXO', models.CharField(max_length=255, null=True, verbose_name='Sexo')),
            ],
        ),
    ]
