# Generated by Django 3.2.6 on 2021-09-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0026_matriculadossexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculadossexo',
            name='COD_UTP',
        ),
    ]
