# Generated by Django 3.2.6 on 2021-10-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0027_remove_matriculadossexo_cod_utp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendencia',
            name='COD_UTP',
        ),
    ]
