# Generated by Django 3.2.6 on 2021-10-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0028_remove_tendencia_cod_utp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatriculadosSexo',
        ),
    ]
