# Generated by Django 3.2.6 on 2021-10-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0029_delete_matriculadossexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisiscohorte',
            name='NIVEL',
            field=models.CharField(max_length=255, null=True, verbose_name='NIVEL'),
        ),
        migrations.AddField(
            model_name='analisiscohorte',
            name='NOMBRE',
            field=models.CharField(max_length=255, null=True, verbose_name='NOMBRE'),
        ),
    ]
