# Generated by Django 3.2.6 on 2021-11-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0030_auto_20211022_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desercion_INTERANUAL_ESTADOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PERIODOS', models.CharField(max_length=255, null=True, verbose_name='Periodos')),
                ('COD_PERIODO', models.CharField(max_length=255, null=True, verbose_name='Semestre')),
                ('NOMBRE', models.CharField(max_length=255, null=True, verbose_name='Nombre')),
                ('NIVEL', models.CharField(max_length=255, null=True, verbose_name='Nivel')),
                ('NO_MATRICULADO', models.IntegerField(null=True, verbose_name='No matriculado')),
                ('PERMANECE_PROGRAMA', models.IntegerField(null=True, verbose_name='Permanece Programa')),
                ('CAMBIO_DE_PROGRAMA', models.IntegerField(null=True, verbose_name='Cambio de programa')),
                ('GRADUADO', models.IntegerField(null=True, verbose_name='Graduado')),
                ('PORCENTAJE_NO_MATRICULADO', models.FloatField(null=True, verbose_name='Porcentaje No matriculado')),
                ('PORCENTAJE_PERMANECE_PROGRAMA', models.FloatField(null=True, verbose_name='Porcentaje Permanece programa')),
                ('PORCENTAJE_CAMBIO_DE_PROGRAMA', models.FloatField(null=True, verbose_name='Porcentaje Cambio de programa')),
                ('PORCENTAJE_GRADUADO', models.FloatField(null=True, verbose_name='Porcentaje Graduado')),
                ('TOTAL', models.IntegerField(null=True, verbose_name='Total')),
            ],
        ),
        migrations.RemoveField(
            model_name='analisiscohorte',
            name='NIVEL',
        ),
        migrations.RemoveField(
            model_name='analisiscohorte',
            name='NOMBRE',
        ),
    ]
