# Generated by Django 3.2.6 on 2021-11-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0031_auto_20211101_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desercion_INTERANUAL_ESTADOS',
            new_name='DesercionInterAnualEstados',
        ),
    ]
