# Generated by Django 3.2.6 on 2021-11-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0032_rename_desercion_interanual_estados_desercioninteranualestados'),
    ]

    operations = [
        migrations.AddField(
            model_name='desercioninteranualestados',
            name='COD_UTP',
            field=models.CharField(max_length=255, null=True, verbose_name='COD_UTP'),
        ),
    ]
