# Generated by Django 3.2.6 on 2021-11-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0033_desercioninteranualestados_cod_utp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desercioninteranualestados',
            name='PERIODOS',
        ),
    ]
