# Generated by Django 3.2.6 on 2021-11-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0034_remove_desercioninteranualestados_periodos'),
    ]

    operations = [
        migrations.AddField(
            model_name='desercioninteranualestados',
            name='PERIODOS',
            field=models.CharField(max_length=255, null=True, verbose_name='PERIODOS'),
        ),
    ]
