# Generated by Django 3.2.6 on 2021-11-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0035_desercioninteranualestados_periodos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desercioninteranualestados',
            name='PERIODOS',
        ),
    ]
